# -*- coding: utf-8 -*-
"""AIHC exp 5 NER.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XmowNINGsq1Yb9SGAK4sP6hOmHuX-5WU

Experiment No. 5: Perform Natural language Entity Extraction from medical
reports

Name: Dhanashree Raut

Department: Comps
"""

pip install -U spacy

!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.1/en_core_sci_sm-0.5.1.tar.gz
!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.1/en_core_sci_md-0.5.1.tar.gz
!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.1/en_ner_bc5cdr_md-0.5.1.tar.gz

pip install render

import spacy
#Core models
import en_core_sci_sm
import en_core_sci_md
#NER specific models
import en_ner_bc5cdr_md
#Tools for extracting & displaying data
from spacy import displacy
import pandas as pd
import render

text="patient is having throat pain. so we gave azee 250"
nlp_sm = en_core_sci_sm.load()
doc = nlp_sm(text)

doc

displacy_image = displacy.render(doc, jupyter=True,style='ent')

import en_core_sci_md
from spacy import displacy
nlp_md = en_core_sci_md.load()
doc = nlp_md(text)
#Display resulting entity extraction
displacy_image = displacy.render(doc, jupyter=True,style='ent')
for ent in doc.ents:
    print(ent.text, ent.start_char, ent.end_char, ent.label_)

nlp_bc = en_ner_bc5cdr_md.load()
doc = nlp_bc(text)
#Display resulting entity extraction
displacy_image = displacy.render(doc, jupyter=True,style='ent')