# -*- coding: utf-8 -*-
"""AIHC Exp1  Data pre processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UWB0SlMn-frpWQPjSMsgy7N117YH9_bW

Experiment No. 1: Collect, Clean, Integrate and Transform Healthcare Data based on specific disease

Name: Dhanashree Raut

Department: Comps
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



"""# New Section"""

dataset = pd.read_csv("Data (1).csv")

x= dataset.iloc[:,:-1].values
y= dataset.iloc[:,-1].values
print(y)
print(x)

print(dataset)

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])

"""# New Section"""

print(x)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

print(x)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = np.array(le.fit_transform(y))

print(y)

dataset['Age'].describe()

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

print(x_test)

print(x_train)

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

x_predict = np.array(x_test[:,:])
print(classifier.predict((x_predict)))

accuracy = classifier.score(x_test,y_test)
print(accuracy)

print(y_test)

"""Naive Bayes Classification"""

from sklearn.naive_bayes import GaussianNB
classifier1 = GaussianNB()
classifier1.fit(x_train, y_train)